"""My first DB migrate

Revision ID: 17c3a9b75cf6
Revises: 
Create Date: 2023-03-27 00:17:21.792296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17c3a9b75cf6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('url',
    sa.Column('id_', sa.INTEGER(), nullable=False),
    sa.Column('long', sa.VARCHAR(), nullable=True),
    sa.Column('short', sa.VARCHAR(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id_')
    )
    # ### end Alembic commands ###
